import { Task } from '../types/task';

const now = new Date();
const d = (offsetDays: number) => {
  const date = new Date(now);
  date.setDate(date.getDate() + offsetDays);
  return date.toISOString().split('T')[0];
};

export const MOCK_TASKS: Task[] = [
  // ─── EPIC 1 ────────────────────────────────────────────────────────────────
  {
    id: 'epic-1',
    issueKey: 'BP-1',
    summary: 'User Authentication & Authorization',
    description: 'Implement complete auth system with OAuth and role-based access.',
    issueType: 'epic',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Sarah Johnson',
    reporter: 'Product Team',
    startDate: d(-10),
    endDate: d(30),
    progress: 40,
    parentId: null,
    children: ['story-1', 'story-2', 'story-3'],
    labels: ['auth', 'security'],
    createdAt: d(-15),
    updatedAt: d(-1),
  },
  {
    id: 'story-1',
    issueKey: 'BP-2',
    summary: 'Login & Registration Flow',
    description: 'Build login, registration, and password reset screens.',
    issueType: 'story',
    status: 'done',
    priority: 'high',
    assignee: 'Sarah Johnson',
    reporter: 'Sarah Johnson',
    startDate: d(-10),
    endDate: d(0),
    progress: 100,
    parentId: 'epic-1',
    children: ['subtask-1', 'subtask-2'],
    labels: ['frontend'],
    createdAt: d(-14),
    updatedAt: d(-2),
  },
  {
    id: 'subtask-1',
    issueKey: 'BP-3',
    summary: 'Login page UI',
    description: 'Design and implement the login page.',
    issueType: 'subtask',
    status: 'done',
    priority: 'medium',
    assignee: 'Sarah Johnson',
    reporter: 'Sarah Johnson',
    startDate: d(-10),
    endDate: d(-5),
    progress: 100,
    parentId: 'story-1',
    children: [],
    labels: [],
    createdAt: d(-14),
    updatedAt: d(-5),
  },
  {
    id: 'subtask-2',
    issueKey: 'BP-4',
    summary: 'Password reset email flow',
    description: 'Send password reset email with secure token.',
    issueType: 'subtask',
    status: 'done',
    priority: 'medium',
    assignee: 'Tom Williams',
    reporter: 'Sarah Johnson',
    startDate: d(-5),
    endDate: d(0),
    progress: 100,
    parentId: 'story-1',
    children: [],
    labels: [],
    createdAt: d(-10),
    updatedAt: d(0),
  },
  {
    id: 'story-2',
    issueKey: 'BP-5',
    summary: 'OAuth Integration (Google & GitHub)',
    description: 'Add OAuth 2.0 login with Google and GitHub providers.',
    issueType: 'story',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Tom Williams',
    reporter: 'Sarah Johnson',
    startDate: d(-2),
    endDate: d(10),
    progress: 60,
    parentId: 'epic-1',
    children: ['subtask-3'],
    labels: ['oauth'],
    createdAt: d(-10),
    updatedAt: d(-1),
  },
  {
    id: 'subtask-3',
    issueKey: 'BP-6',
    summary: 'Google OAuth callback handler',
    description: 'Implement the OAuth callback and session creation.',
    issueType: 'subtask',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Tom Williams',
    reporter: 'Tom Williams',
    startDate: d(-2),
    endDate: d(5),
    progress: 70,
    parentId: 'story-2',
    children: [],
    labels: [],
    createdAt: d(-8),
    updatedAt: d(-1),
  },
  {
    id: 'story-3',
    issueKey: 'BP-7',
    summary: 'Role-Based Access Control',
    description: 'Define roles (admin, member, viewer) and enforce permissions.',
    issueType: 'story',
    status: 'todo',
    priority: 'medium',
    assignee: 'Sarah Johnson',
    reporter: 'Sarah Johnson',
    startDate: d(10),
    endDate: d(25),
    progress: 0,
    parentId: 'epic-1',
    children: [],
    labels: ['security'],
    createdAt: d(-5),
    updatedAt: d(-5),
  },

  // ─── EPIC 2 ────────────────────────────────────────────────────────────────
  {
    id: 'epic-2',
    issueKey: 'BP-8',
    summary: 'Dashboard & Analytics',
    description: 'Build main dashboard with KPI widgets and analytics charts.',
    issueType: 'epic',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Alex Chen',
    reporter: 'Product Team',
    startDate: d(-5),
    endDate: d(45),
    progress: 25,
    parentId: null,
    children: ['story-4', 'story-5'],
    labels: ['dashboard', 'analytics'],
    createdAt: d(-20),
    updatedAt: d(-1),
  },
  {
    id: 'story-4',
    issueKey: 'BP-9',
    summary: 'KPI Summary Widgets',
    description: 'Create reusable KPI card components for the dashboard.',
    issueType: 'story',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Alex Chen',
    reporter: 'Alex Chen',
    startDate: d(-5),
    endDate: d(8),
    progress: 50,
    parentId: 'epic-2',
    children: ['subtask-4', 'subtask-5'],
    labels: ['components'],
    createdAt: d(-15),
    updatedAt: d(-1),
  },
  {
    id: 'subtask-4',
    issueKey: 'BP-10',
    summary: 'KPI card component',
    description: 'Base card component with title, value, trend indicator.',
    issueType: 'subtask',
    status: 'done',
    priority: 'medium',
    assignee: 'Alex Chen',
    reporter: 'Alex Chen',
    startDate: d(-5),
    endDate: d(0),
    progress: 100,
    parentId: 'story-4',
    children: [],
    labels: [],
    createdAt: d(-12),
    updatedAt: d(0),
  },
  {
    id: 'subtask-5',
    issueKey: 'BP-11',
    summary: 'Real-time data refresh',
    description: 'Implement WebSocket or polling for live data updates.',
    issueType: 'subtask',
    status: 'in_progress',
    priority: 'medium',
    assignee: 'Alex Chen',
    reporter: 'Alex Chen',
    startDate: d(0),
    endDate: d(8),
    progress: 30,
    parentId: 'story-4',
    children: [],
    labels: [],
    createdAt: d(-10),
    updatedAt: d(-1),
  },
  {
    id: 'story-5',
    issueKey: 'BP-12',
    summary: 'Interactive Charts & Graphs',
    description: 'Add line, bar, and pie charts with drill-down capability.',
    issueType: 'story',
    status: 'todo',
    priority: 'medium',
    assignee: 'Maria Garcia',
    reporter: 'Alex Chen',
    startDate: d(8),
    endDate: d(30),
    progress: 0,
    parentId: 'epic-2',
    children: ['subtask-6'],
    labels: ['charts'],
    createdAt: d(-10),
    updatedAt: d(-5),
  },
  {
    id: 'subtask-6',
    issueKey: 'BP-13',
    summary: 'Revenue trend chart',
    description: 'Line chart showing monthly revenue over the last 12 months.',
    issueType: 'subtask',
    status: 'todo',
    priority: 'low',
    assignee: 'Maria Garcia',
    reporter: 'Maria Garcia',
    startDate: d(10),
    endDate: d(20),
    progress: 0,
    parentId: 'story-5',
    children: [],
    labels: [],
    createdAt: d(-8),
    updatedAt: d(-8),
  },

  // ─── EPIC 3 ────────────────────────────────────────────────────────────────
  {
    id: 'epic-3',
    issueKey: 'BP-14',
    summary: 'Mobile App (iOS & Android)',
    description: 'Launch native mobile apps using React Native.',
    issueType: 'epic',
    status: 'todo',
    priority: 'medium',
    assignee: 'James Lee',
    reporter: 'Product Team',
    startDate: d(20),
    endDate: d(90),
    progress: 0,
    parentId: null,
    children: ['story-6', 'story-7'],
    labels: ['mobile'],
    createdAt: d(-5),
    updatedAt: d(-5),
  },
  {
    id: 'story-6',
    issueKey: 'BP-15',
    summary: 'React Native Setup & Navigation',
    description: 'Initialize RN project, configure navigation and deep linking.',
    issueType: 'story',
    status: 'todo',
    priority: 'high',
    assignee: 'James Lee',
    reporter: 'James Lee',
    startDate: d(20),
    endDate: d(35),
    progress: 0,
    parentId: 'epic-3',
    children: [],
    labels: ['setup'],
    createdAt: d(-3),
    updatedAt: d(-3),
  },
  {
    id: 'story-7',
    issueKey: 'BP-16',
    summary: 'Push Notifications',
    description: 'Implement push notifications via Firebase Cloud Messaging.',
    issueType: 'story',
    status: 'todo',
    priority: 'medium',
    assignee: 'James Lee',
    reporter: 'James Lee',
    startDate: d(35),
    endDate: d(55),
    progress: 0,
    parentId: 'epic-3',
    children: ['subtask-7'],
    labels: ['notifications'],
    createdAt: d(-3),
    updatedAt: d(-3),
  },
  {
    id: 'subtask-7',
    issueKey: 'BP-17',
    summary: 'FCM token registration',
    description: 'Register device FCM token on login and store server-side.',
    issueType: 'subtask',
    status: 'todo',
    priority: 'medium',
    assignee: 'James Lee',
    reporter: 'James Lee',
    startDate: d(35),
    endDate: d(42),
    progress: 0,
    parentId: 'story-7',
    children: [],
    labels: [],
    createdAt: d(-3),
    updatedAt: d(-3),
  },
  // ─── A standalone bug ────────────────────────────────────────────────────
  {
    id: 'bug-1',
    issueKey: 'BP-18',
    summary: 'Fix memory leak in WebSocket connection',
    description: 'WebSocket connections are not properly cleaned up on component unmount.',
    issueType: 'bug',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Tom Williams',
    reporter: 'Alex Chen',
    startDate: d(-3),
    endDate: d(3),
    progress: 50,
    parentId: null,
    children: [],
    labels: ['bugfix'],
    createdAt: d(-4),
    updatedAt: d(-1),
  },
];

export const MOCK_LINKS = [
  { id: 'link-1', source: 'story-1', target: 'story-2', type: 'e2s' },
  { id: 'link-2', source: 'story-4', target: 'story-5', type: 'e2s' },
  { id: 'link-3', source: 'story-6', target: 'story-7', type: 'e2s' },
];
